/** Remote runtime shape of the wasm-bindgen output (crates/tabverse-web/pkg, generated by
 * tools/build-web.sh with --no-typescript). Only what the page calls. */
declare module "*/pkg/tabverse_web.js" {
  /** wasm-bindgen's default init: fetches/instantiates the module. */
  export default function __wbg_init(options?: {
    module_or_path?: string | URL | Request | BufferSource | WebAssembly.Module;
  }): Promise<unknown>;
  export function joinShare(
    ticket: string,
    clientName: string,
    onEvent: (json: string) => void
  ): Promise<unknown>;
}
