use std::path::Path;

fn main() {
    generate_declared_associations();
    generate_theme_constants();
    tauri_build::build()
}

/// Bake the claimed file types into the binary, read from the same
/// tauri.conf.json the bundler reads.
///
/// This exists because the config the app can see at runtime does NOT contain
/// them: Tauri's code generation writes `file_associations: None` into the
/// embedded config unconditionally, so `app.config().bundle.file_associations`
/// is always empty no matter what the file says. Reading it there looked
/// right, compiled, passed its unit tests, and produced a default-editor
/// switch with nothing to claim — the failure was invisible until the switch
/// was driven against a real installed bundle.
///
/// Generating from the config keeps one source of truth: add a suffix to
/// tauri.conf.json and both the installer's declaration and the switch that
/// claims it move together.
fn generate_declared_associations() {
    let conf_path = Path::new("tauri.conf.json");
    println!("cargo:rerun-if-changed=tauri.conf.json");
    let conf: serde_json::Value = serde_json::from_str(
        &std::fs::read_to_string(conf_path).expect("tauri.conf.json is unreadable"),
    )
    .expect("tauri.conf.json is not valid JSON");

    let associations = conf
        .get("bundle")
        .and_then(|b| b.get("fileAssociations"))
        .and_then(|f| f.as_array())
        .cloned()
        .unwrap_or_default();

    // Declared but never claimed as default. The file tab can open these, but
    // the double-click intent is served better elsewhere: extraction for an
    // archive, the real Office apps for a document, playback for media,
    // installing for a font. Declaring keeps the app in the "Open with" menu;
    // claiming is reserved for what it genuinely serves as a first choice.
    let declare_only: Vec<String> = conf
        .get("plugins")
        .and_then(|p| p.get("default-apps"))
        .and_then(|d| d.get("declareOnly"))
        .and_then(|l| l.as_array())
        .map(|l| {
            l.iter()
                .filter_map(|v| v.as_str().map(String::from))
                .collect()
        })
        .unwrap_or_default();

    let mut out = String::from(
        "// Generated by build.rs from tauri.conf.json. Do not edit.\n\
         //\n\
         // One entry per `bundle.fileAssociations` entry, in the same order.\n\n\
         #[allow(dead_code)]\n\
         pub struct DeclaredAssociation {\n\
         \x20   pub name: &'static str,\n\
         \x20   pub ext: &'static [&'static str],\n\
         \x20   pub content_types: &'static [&'static str],\n\
         \x20   pub mime_type: Option<&'static str>,\n\
         \x20   /// The app runs these rather than opening them: the `Shell`\n\
         \x20   /// role. What separates the terminal switch from the editor one.\n\
         \x20   pub executes: bool,\n\
         \x20   /// False for types that are declared (so the app appears in\n\
         \x20   /// \"Open with\") but never set as the default: the double-click\n\
         \x20   /// intent is served better by another app.\n\
         \x20   pub claims_default: bool,\n\
         }\n\n\
         pub static DECLARED: &[DeclaredAssociation] = &[\n",
    );

    for a in &associations {
        let name = a.get("name").and_then(|v| v.as_str()).unwrap_or_default();
        let exts: Vec<&str> = a
            .get("ext")
            .and_then(|v| v.as_array())
            .map(|v| v.iter().filter_map(|e| e.as_str()).collect())
            .unwrap_or_default();
        let types: Vec<&str> = a
            .get("contentTypes")
            .and_then(|v| v.as_array())
            .map(|v| v.iter().filter_map(|e| e.as_str()).collect())
            .unwrap_or_default();
        let mime = a.get("mimeType").and_then(|v| v.as_str());
        let executes = a.get("role").and_then(|v| v.as_str()) == Some("Shell");

        out.push_str("    DeclaredAssociation {\n");
        out.push_str(&format!("        name: {name:?},\n"));
        out.push_str(&format!(
            "        ext: &{:?},\n",
            exts.iter()
                .map(|s| s.trim_start_matches('.'))
                .collect::<Vec<_>>()
        ));
        out.push_str(&format!("        content_types: &{types:?},\n"));
        out.push_str(&match mime {
            Some(m) => format!("        mime_type: Some({m:?}),\n"),
            None => "        mime_type: None,\n".to_string(),
        });
        out.push_str(&format!("        executes: {executes},\n"));
        let claims = !declare_only.iter().any(|n| n == name);
        out.push_str(&format!("        claims_default: {claims},\n"));
        out.push_str("    },\n");
    }
    out.push_str("];\n");

    let dest =
        Path::new(&std::env::var("OUT_DIR").expect("no OUT_DIR")).join("declared_associations.rs");
    std::fs::write(&dest, out).expect("cannot write the generated association list");
}

fn generate_theme_constants() {
    let tokens_path = Path::new("../packages/workbench/src/theme/tokens.json");
    println!("cargo:rerun-if-changed=../packages/workbench/src/theme/tokens.json");
    let tokens: serde_json::Value = serde_json::from_str(
        &std::fs::read_to_string(tokens_path)
            .expect("../packages/workbench/src/theme/tokens.json is unreadable"),
    )
    .expect("tokens.json is not valid JSON");

    let themes = tokens
        .get("themes")
        .and_then(|t| t.as_object())
        .expect("tokens.json has no themes object");
    let theme_bg = |theme: &str| -> String {
        themes
            .get(theme)
            .and_then(|t| t.get("color"))
            .and_then(|c| c.get("bg"))
            .and_then(|v| v.as_str())
            .unwrap_or_else(|| panic!("tokens.json has no themes.{theme}.color.bg"))
            .to_string()
    };
    let theme_is_dark = |theme: &str| -> bool {
        match themes
            .get(theme)
            .and_then(|t| t.get("appearance"))
            .and_then(|v| v.as_str())
        {
            Some("dark") => true,
            Some("light") => false,
            other => panic!("themes.{theme}.appearance is {other:?}, not \"light\" or \"dark\""),
        }
    };
    let find_hl = |key: &str| -> String {
        tokens
            .get("shared")
            .and_then(|s| s.get("findHighlight"))
            .and_then(|f| f.get(key))
            .and_then(|v| v.as_str())
            .unwrap_or_else(|| panic!("tokens.json has no shared.findHighlight.{key}"))
            .to_string()
    };

    // #rrggbb only: the backdrop goes to NSColor as sRGB fractions, and a
    // shorthand or alpha form here would mean tokens.json changed contract.
    fn rgb(hex: &str) -> (u8, u8, u8) {
        let ok = hex.len() == 7 && hex.starts_with('#');
        let byte = |i: usize| u8::from_str_radix(&hex[i..i + 2], 16);
        match (ok, byte(1), byte(3), byte(5)) {
            (true, Ok(r), Ok(g), Ok(b)) => (r, g, b),
            _ => panic!("theme bg {hex:?} is not a #rrggbb color"),
        }
    }

    let mut out = String::from(
        "// Generated by build.rs from packages/workbench/src/theme/tokens.json. Do not edit.\n\
         //\n\
         // The window backdrop (themes.*.color.bg) as sRGB fractions, and the\n\
         // find-in-page highlight (shared.findHighlight) as CSS color literals.\n\n\
         pub struct Backdrop {\n\
         \x20   pub r: f64,\n\
         \x20   pub g: f64,\n\
         \x20   pub b: f64,\n\
         }\n\n\
         /// One row per theme in tokens.json: its id, whether it reads dark,\n\
         /// and the window color to paint behind it.\n\
         pub struct Theme {\n\
         \x20   pub id: &'static str,\n\
         \x20   pub dark: bool,\n\
         \x20   pub backdrop: Backdrop,\n\
         }\n\n",
    );

    out.push_str(
        "/// Every theme tokens.json declares, ordered by id — the whole of\n\
         /// what the Rust side knows about themes. A theme added to\n\
         /// tokens.json appears here on the next build, with no Rust edit.\n\
         pub static THEMES: &[Theme] = &[\n",
    );
    for theme in themes.keys() {
        let hex = theme_bg(theme);
        let (r, g, b) = rgb(&hex);
        let dark = theme_is_dark(theme);
        out.push_str(&format!(
            "    // themes.{theme}.color.bg = {hex:?}\n\
             \x20   Theme {{\n\
             \x20       id: {theme:?},\n\
             \x20       dark: {dark},\n\
             \x20       backdrop: Backdrop {{\n\
             \x20           r: {r}f64 / 255.0,\n\
             \x20           g: {g}f64 / 255.0,\n\
             \x20           b: {b}f64 / 255.0,\n\
             \x20       }},\n\
             \x20   }},\n"
        ));
    }
    out.push_str("];\n\n");

    out.push_str(
        "/// The row for a theme id, or None when tokens.json has no such\n\
         /// theme — the one place an id from disk or from the interface is\n\
         /// turned into something paintable.\n\
         pub fn theme(id: &str) -> Option<&'static Theme> {\n\
         \x20   THEMES.iter().find(|t| t.id == id)\n\
         }\n\n\
         /// The backdrop for an OS appearance rather than a named theme —\n\
         /// what the \"system\" preference resolves to, which can only ever\n\
         /// be one of the two built-ins because the OS reports nothing finer.\n\
         /// Matched on the id AND the appearance, so a built-in whose\n\
         /// appearance was edited to disagree with its name cannot be handed\n\
         /// back for the wrong OS mode. Both built-ins are required by\n\
         /// tokens.schema.json, so the search cannot come back empty; if it\n\
         /// somehow did, any theme is still a real color and a panic here\n\
         /// would cost the window it is meant to paint.\n\
         pub fn backdrop(dark: bool) -> &'static Backdrop {\n\
         \x20   let want = if dark { \"dark\" } else { \"light\" };\n\
         \x20   let row = THEMES\n\
         \x20       .iter()\n\
         \x20       .find(|t| t.id == want && t.dark == dark)\n\
         \x20       .unwrap_or(&THEMES[0]);\n\
         \x20   &row.backdrop\n\
         }\n\n",
    );
    for (name, key) in [
        ("FIND_HL_BG", "bg"),
        ("FIND_HL_FG", "fg"),
        ("FIND_HL_CUR_BG", "currentBg"),
        ("FIND_HL_CUR_FG", "currentFg"),
    ] {
        out.push_str(&format!("pub const {name}: &str = {:?};\n", find_hl(key)));
    }

    let dest = Path::new(&std::env::var("OUT_DIR").expect("no OUT_DIR")).join("theme_generated.rs");
    std::fs::write(&dest, out).expect("cannot write the generated theme constants");
}
