//! Shell integration without touching the user's dotfiles.
//!
//! We need the shell to emit OSC 133 (prompt/command/exit markers) and OSC 7
//! (working directory) so the UI can split output into command blocks. Editing
//! `~/.zshrc` to get that is intrusive and hard to undo, so instead we generate
//! a private startup directory and point the shell at it; our snippet sources
//! the user's own config first and then adds the markers.

use anyhow::{Context, Result};
use std::path::{Path, PathBuf};

/// Where generated integration files live (`~/.tabverse/shell`).
pub fn integration_dir() -> Result<PathBuf> {
    let home = crate::home_dir().context("neither HOME nor USERPROFILE is set")?;
    Ok(Path::new(&home).join(".tabverse").join("shell"))
}

/// `.zshenv` — zsh reads this first, for every shell.
///
/// Pointing ZDOTDIR at our directory makes zsh look for *all* of its startup
/// files here, so each one has to hand control back to the user's own. Missing
/// this is how a terminal ends up without Homebrew on PATH: `brew shellenv`
/// lives in `.zprofile`, which zsh would otherwise never read.
const ZSHENV: &str = r#"# Generated by Tabverse. Rewritten on every launch; do not edit.
# Remember where the user's real startup files live, then keep ZDOTDIR pointed
# at our directory so the remaining stages still come through here.
: ${TABVERSE_DIR:="${ZDOTDIR}"}
export TABVERSE_DIR
if [ -z "$TABVERSE_USER_ZDOTDIR" ]; then
  export TABVERSE_USER_ZDOTDIR="$HOME"
fi

[ -f "$TABVERSE_USER_ZDOTDIR/.zshenv" ] && builtin source "$TABVERSE_USER_ZDOTDIR/.zshenv"

# A user who sets ZDOTDIR inside their own .zshenv would divert the rest of the
# startup sequence away from us; take the new value as their real home and
# restore our own for the remaining stages.
if [ "$ZDOTDIR" != "$TABVERSE_DIR" ]; then
  export TABVERSE_USER_ZDOTDIR="$ZDOTDIR"
  export ZDOTDIR="$TABVERSE_DIR"
fi
"#;

/// `.zprofile` — login shells only. This is where Homebrew puts its PATH setup.
const ZPROFILE: &str = r#"# Generated by Tabverse. Rewritten on every launch; do not edit.
[ -f "$TABVERSE_USER_ZDOTDIR/.zprofile" ] && builtin source "$TABVERSE_USER_ZDOTDIR/.zprofile"
"#;

const ZSHRC: &str = r#"# Generated by Tabverse. Sources your own config, then adds shell integration.
# Do not edit: this file is rewritten on every launch.

_tabverse_source_user() {
  [ -f "$TABVERSE_USER_ZDOTDIR/.zshrc" ] && builtin source "$TABVERSE_USER_ZDOTDIR/.zshrc"
}
_tabverse_source_user

# --- OSC 133 command blocks + OSC 7 working directory -----------------------
_tabverse_osc7() {
  printf '\e]7;file://%s%s\e\\' "${HOST:-localhost}" "$PWD"
}

_tabverse_preexec() {
  # 133;C marks "command starts running"; the base64 payload lets the UI show
  # the command line even when the prompt redraws over it.
  local cmd_b64
  cmd_b64=$(printf '%s' "$1" | base64 | tr -d '\n')
  printf '\e]133;C;cmdline_b64=%s\a' "$cmd_b64"
}

_tabverse_precmd() {
  local exit_code=$?
  printf '\e]133;D;%s\a' "$exit_code"
  _tabverse_osc7
  # 133;A marks "prompt starts"; 133;B marks "prompt ends, input begins".
  printf '\e]133;A\a'
}

autoload -Uz add-zsh-hook 2>/dev/null || true
if command -v add-zsh-hook >/dev/null 2>&1; then
  add-zsh-hook preexec _tabverse_preexec
  add-zsh-hook precmd _tabverse_precmd
else
  precmd_functions+=(_tabverse_precmd)
  preexec_functions+=(_tabverse_preexec)
fi

# No startup output here: zsh runs precmd before the very first prompt, so the
# hooks cover it — and frameworks like powerlevel10k's instant prompt treat any
# console output during rc as an error worth a warning banner.

# Mark the end of the prompt right before the shell reads input.
if [[ -n "$PS1" ]]; then
  PS1="$PS1"$'%{\e]133;B\a%}'
fi

# Every startup file of ours has run, so hand ZDOTDIR back. Nested shells and
# tools that read it now see the user's own value, and zsh looks for .zlogin
# where the user actually keeps it.
if [ "$TABVERSE_USER_ZDOTDIR" = "$HOME" ]; then
  unset ZDOTDIR
else
  export ZDOTDIR="$TABVERSE_USER_ZDOTDIR"
fi
unset TABVERSE_DIR
"#;

const BASHRC: &str = r#"# Generated by Tabverse. Sources your own config, then adds shell integration.
# Do not edit: this file is rewritten on every launch.

# --rcfile implies a non-login shell, which would skip the profile files where
# PATH is usually set up (Homebrew writes to ~/.bash_profile). Mirror a real
# login bash exactly: /etc/profile first (on macOS that is what runs
# path_helper), then the first user profile file that exists — and nothing
# more. A login bash never sources ~/.bashrc itself; profiles that want it
# source it themselves, so a fallback here would run .bashrc a second time in
# the common macOS setup where .bash_profile already sources it (duplicated
# PATH entries, nvm/rbenv initialized twice). A user whose config lives only
# in .bashrc gets what Terminal.app's login shell gives them — nothing —
# which is correct login semantics.
[ -f /etc/profile ] && builtin source /etc/profile
if [ -f "$HOME/.bash_profile" ]; then
  . "$HOME/.bash_profile"
elif [ -f "$HOME/.bash_login" ]; then
  . "$HOME/.bash_login"
elif [ -f "$HOME/.profile" ]; then
  . "$HOME/.profile"
fi

_tabverse_osc7() {
  printf '\033]7;file://%s%s\033\\' "${HOSTNAME:-localhost}" "$PWD"
}

# Report the first command after each prompt. The flag is what keeps the
# user's own PROMPT_COMMAND from being reported as if it were their command:
# DEBUG fires for those too, and they run *after* ours.
_tabverse_preexec() {
  [ -n "$COMP_LINE" ] && return                 # tab completion, not a command
  [ -z "$_TABVERSE_AT_PROMPT" ] && return       # already reported this one
  [ "$BASH_SUBSHELL" != "0" ] && return
  _TABVERSE_AT_PROMPT=
  local cmd_b64
  cmd_b64=$(printf '%s' "$BASH_COMMAND" | base64 | tr -d '\n')
  printf '\033]133;C;cmdline_b64=%s\a' "$cmd_b64"
}

_tabverse_precmd() {
  local exit_code=$?
  printf '\033]133;D;%s\a' "$exit_code"
  _tabverse_osc7
  printf '\033]133;A\a'
  # Set last: everything after this point is the user typing, not the prompt.
  _TABVERSE_AT_PROMPT=1
}

trap '_tabverse_preexec' DEBUG
# Appended, not prepended: ours must run after the user's so that the flag is
# set once their prompt work is done.
PROMPT_COMMAND="${PROMPT_COMMAND:+$PROMPT_COMMAND; }_tabverse_precmd"
PS1="$PS1\[\033]133;B\a\]"
# No startup markers: PROMPT_COMMAND runs before the first prompt too.
_TABVERSE_AT_PROMPT=1
"#;

const FISHRC: &str = r#"# Generated by Tabverse. Rewritten on every launch; do not edit.
#
# fish has no ZDOTDIR, so this file arrives through
# `fish -C "source $TABVERSE_FISH_INIT"`. Despite the option's name, -C
# commands run AFTER ~/.config/fish/conf.d and config.fish (verified against
# fish 4.5.0), which puts the direction on the same footing as the zsh
# snippets: the user's config has already run — exactly once, by fish itself —
# by the time these hooks install. ZDOTDIR displaces the user's zsh startup
# files, which is why those snippets forward every stage themselves; -C
# displaces nothing, and sourcing config.fish from here would only run it a
# second time (aliases re-defined, prompt frameworks initialized twice).

# --- OSC 133 command blocks + OSC 7 working directory -----------------------
function _tabverse_osc7
    set -q hostname; or set -l hostname localhost
    printf '\e]7;file://%s%s\e\\' "$hostname" $PWD
end

# 133;C marks "command starts running"; the base64 payload lets the UI show
# the command line even when the prompt redraws over it. base64 wraps its
# output at 76 columns; command substitution splits those lines apart and
# `string join` glues them back, so the payload stays on one line — the UI's
# cmdline_b64 matcher only accepts [A-Za-z0-9+/=]. fish >= 4.0 also emits its
# own OSC 133 with a cmdline_url= payload the UI cannot read and would
# double-book, so prepare() passes `--features no-mark-prompt` to silence the
# built-ins on fish that knows the flag (>= 4.0.6); older fish never shipped
# it and keep the duplicated markers, since no flag exists there to remove.
function _tabverse_preexec --on-event fish_preexec
    set -l cmd_b64 (printf '%s' $argv[1] | base64 | string join '')
    printf '\e]133;C;cmdline_b64=%s\a' $cmd_b64
end

# D rides the fish_prompt event rather than fish_postexec: that keeps the zsh
# precmd shape (one place emits D + OSC 7 + A), and $status still holds the
# previous command's exit there (verified: 1 after `false`, 0 after `true`).
# postexec would add nothing — it cannot fire for commands that replace the
# shell image, and those never draw another prompt either, so both placements
# lose the same markers.
function _tabverse_precmd --on-event fish_prompt
    printf '\e]133;D;%s\a' $status
    _tabverse_osc7
    printf '\e]133;A\a'
end

# 133;B marks "prompt ends, input begins" and must be the last bytes the
# prompt produces. -C runs after the user's config, so their fish_prompt (or
# fish's autoloaded default — `functions -c` resolves either) is already in
# place to copy and re-define with B appended. The guard keeps a re-source of
# this file from wrapping the wrapper into itself.
if not functions -q __tabverse_user_prompt
    functions -c fish_prompt __tabverse_user_prompt
    function fish_prompt
        __tabverse_user_prompt
        printf '\e]133;B\a'
    end
end
"#;

const PWSH_INIT: &str = r##"# Generated by Tabverse. Rewritten on every launch; do not edit.
#
# pwsh is launched as
# `pwsh -NoLogo -NoExit -Command ". $env:TABVERSE_PWSH_INIT"`. -Command runs
# after the user's profiles, so like the fish and zsh snippets this file only
# wraps what the user's own setup already defined; their prompt function
# (oh-my-posh or otherwise) is kept and re-emitted inside the wrapper. pwsh is
# not installed on this repo's dev machine, so this script is asserted by
# shape, never executed here — live behavior is a Windows-side boundary.

$global:__tabverse_user_prompt = $function:prompt

$function:prompt = {
    # $? carries PowerShell's own success flag; $LASTEXITCODE the exit code of
    # the last *native* command. Both are read before anything else runs, or
    # the wrapper's own calls would clobber them.
    $exit = 0
    if (-not $?) {
        if ($LASTEXITCODE -is [int] -and $LASTEXITCODE -ne 0) { $exit = $LASTEXITCODE }
        else { $exit = 1 }
    }
    $esc = [char]27
    $bel = [char]7
    [Console]::Write("$esc]133;D;$exit$bel")
    # .Path, not the stringified $PWD: the latter can be a provider path
    # (Registry::HKEY_...) that names no filesystem location.
    [Console]::Write("$esc]7;file://$([System.Net.Dns]::GetHostName())$($PWD.Path)$esc\")
    [Console]::Write("$esc]133;A$bel")
    # Write-Host renders before the function's return value, so B rides the
    # returned prompt string to land after the user's prompt text.
    "$(& $global:__tabverse_user_prompt)$esc]133;B$bel"
}

$global:__tabverse_user_readline = $function:PSConsoleHostReadLine
function global:PSConsoleHostReadLine {
    # PSConsoleHostReadLine is unset by default; PSConsoleReadLine::ReadLine is
    # what the host itself would call. If the user's profile defined their own,
    # chain to it instead.
    if ($global:__tabverse_user_readline) {
        $line = & $global:__tabverse_user_readline
    } else {
        $line = [Microsoft.PowerShell.PSConsoleReadLine]::ReadLine($host.Runspace, $ExecutionContext)
    }
    # The line is about to execute: emit C with the command line base64'd.
    # Empty lines never reach a shell's preexec in zsh/fish; skip them here too.
    if ($line) {
        $b64 = [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($line))
        [Console]::Write("$([char]27)]133;C;cmdline_b64=$b64$([char]7)")
    }
    $line
}
"##;

/// Whether this fish build knows the `no-mark-prompt` feature (added 4.0.6).
///
/// fish >= 4.0 emits its own OSC 133 markers carrying `cmdline_url=` payloads
/// the UI cannot read, and the frontend would book a second, empty block for
/// every command next to ours; `--features no-mark-prompt` silences the
/// built-ins. The flag is gated on a version probe rather than passed
/// unconditionally: a fish old enough not to ship the feature might not
/// tolerate the unknown value, and a spawn-time error there would cost the
/// user their shell, not just their markers.
fn fish_knows_no_mark_prompt(shell_path: &str) -> bool {
    let Ok(out) = std::process::Command::new(shell_path)
        .arg("--version")
        .output()
    else {
        return false;
    };
    if !out.status.success() {
        return false;
    }
    fish_version(&String::from_utf8_lossy(&out.stdout))
        .map(|v| v >= (4, 0, 6))
        .unwrap_or(false)
}

/// Parse `fish, version 4.5.0` into `(4, 5, 0)`.
fn fish_version(text: &str) -> Option<(u32, u32, u32)> {
    let mut parts = text.trim().rsplit(' ').next()?.split('.');
    let major = parts.next()?.parse().ok()?;
    let minor = parts.next()?.parse().ok()?;
    let patch = parts.next().unwrap_or("0").parse().ok()?;
    Some((major, minor, patch))
}

/// Write the integration files and return the env vars a shell needs.
///
/// Returns an empty list for shells we have no integration for; those still
/// work, just without command blocks.
pub fn prepare(shell_path: &str) -> Result<Vec<(String, String)>> {
    let dir = integration_dir()?;
    std::fs::create_dir_all(&dir).with_context(|| format!("cannot create {}", dir.display()))?;

    let shell_name = Path::new(shell_path)
        .file_name()
        .map(|s| s.to_string_lossy().to_string())
        .unwrap_or_default();

    match shell_name.as_str() {
        "zsh" => {
            // All four stages, or zsh silently skips the ones we don't provide.
            std::fs::write(dir.join(".zshenv"), ZSHENV)?;
            std::fs::write(dir.join(".zprofile"), ZPROFILE)?;
            std::fs::write(dir.join(".zshrc"), ZSHRC)?;
            let mut env = vec![
                ("ZDOTDIR".to_string(), dir.to_string_lossy().to_string()),
                ("TABVERSE_SHELL_INTEGRATION".to_string(), "1".to_string()),
            ];
            // Preserve a custom ZDOTDIR so the generated rc can hand it back.
            if let Ok(user) = std::env::var("ZDOTDIR") {
                env.push(("TABVERSE_USER_ZDOTDIR".to_string(), user));
            }
            Ok(env)
        }
        "bash" => {
            let rc = dir.join("bashrc");
            std::fs::write(&rc, BASHRC)?;
            Ok(vec![
                (
                    "TABVERSE_BASH_RC".to_string(),
                    rc.to_string_lossy().to_string(),
                ),
                ("TABVERSE_SHELL_INTEGRATION".to_string(), "1".to_string()),
            ])
        }
        "fish" => {
            let init = dir.join("fish_init.fish");
            std::fs::write(&init, FISHRC)?;
            let mut env = vec![
                (
                    "TABVERSE_FISH_INIT".to_string(),
                    init.to_string_lossy().to_string(),
                ),
                ("TABVERSE_SHELL_INTEGRATION".to_string(), "1".to_string()),
            ];
            if fish_knows_no_mark_prompt(shell_path) {
                env.push(("TABVERSE_FISH_NO_MARK".to_string(), "1".to_string()));
            }
            Ok(env)
        }
        // "pwsh.exe" is what a Windows path's basename ends up as.
        "pwsh" | "pwsh.exe" => {
            let init = dir.join("pwsh_init.ps1");
            std::fs::write(&init, PWSH_INIT)?;
            Ok(vec![
                (
                    "TABVERSE_PWSH_INIT".to_string(),
                    init.to_string_lossy().to_string(),
                ),
                ("TABVERSE_SHELL_INTEGRATION".to_string(), "1".to_string()),
            ])
        }
        _ => Ok(vec![]),
    }
}

/// Extra command-line arguments needed to load the integration.
pub fn args_for(shell_path: &str, env: &[(String, String)]) -> Vec<String> {
    let shell_name = Path::new(shell_path)
        .file_name()
        .map(|s| s.to_string_lossy().to_string())
        .unwrap_or_default();
    if shell_name == "bash" {
        if let Some((_, rc)) = env.iter().find(|(k, _)| k == "TABVERSE_BASH_RC") {
            // bash has no ZDOTDIR equivalent; --rcfile is the only hook, and it
            // implies an interactive non-login shell.
            return vec!["--rcfile".to_string(), rc.clone(), "-i".to_string()];
        }
    }
    if shell_name == "fish" && env.iter().any(|(k, _)| k == "TABVERSE_FISH_INIT") {
        let mut args = Vec::new();
        if env.iter().any(|(k, _)| k == "TABVERSE_FISH_NO_MARK") {
            args.push("--features".to_string());
            args.push("no-mark-prompt".to_string());
        }
        args.push("-C".to_string());
        // The path rides in $TABVERSE_FISH_INIT rather than being inlined:
        // as a variable it needs no quoting whatever the user's home
        // directory contains.
        args.push("source $TABVERSE_FISH_INIT".to_string());
        return args;
    }
    if matches!(shell_name.as_str(), "pwsh" | "pwsh.exe")
        && env.iter().any(|(k, _)| k == "TABVERSE_PWSH_INIT")
    {
        // pwsh has no rcfile; -Command runs after the user's profiles and
        // -NoExit keeps the session alive after the init script. The path
        // rides in $env:TABVERSE_PWSH_INIT for the same quoting-free
        // reason as fish's.
        return vec![
            "-NoLogo".to_string(),
            "-NoExit".to_string(),
            "-Command".to_string(),
            ". $env:TABVERSE_PWSH_INIT".to_string(),
        ];
    }
    vec![]
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::{Mutex, MutexGuard};

    /// prepare() resolves its output directory from $HOME, so a test that runs
    /// it against the real environment writes into the actual user home. Swap
    /// HOME for a scratch directory instead — and because HOME is
    /// process-global while cargo runs tests on parallel threads, hold a lock
    /// for the whole swap and restore the old value before releasing it.
    static HOME_LOCK: Mutex<()> = Mutex::new(());

    struct ScratchHome {
        _lock: MutexGuard<'static, ()>,
        prev: Option<String>,
    }

    fn scratch_home(tag: &str) -> ScratchHome {
        // A poisoned lock only means another test failed; the env swap below
        // is still safe to perform.
        let lock = HOME_LOCK.lock().unwrap_or_else(|e| e.into_inner());
        let dir =
            std::env::temp_dir().join(format!("tabverse-unit-home-{tag}-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).unwrap();
        let prev = std::env::var("HOME").ok();
        std::env::set_var("HOME", &dir);
        ScratchHome { _lock: lock, prev }
    }

    impl Drop for ScratchHome {
        fn drop(&mut self) {
            // Restore while the lock is still held, so no other test observes
            // the scratch value. The directory itself is left for the OS temp
            // cleaner: a test in another module may have read HOME while it
            // pointed here and still hold a path into it.
            match &self.prev {
                Some(v) => std::env::set_var("HOME", v),
                None => std::env::remove_var("HOME"),
            }
        }
    }

    #[test]
    fn zsh_integration_is_self_contained() {
        let _home = scratch_home("zsh");
        let env = prepare("/bin/zsh").expect("prepare zsh");
        let dir = integration_dir().unwrap();
        let rc = std::fs::read_to_string(dir.join(".zshrc")).expect("zshrc written");

        // It must emit both marker families, or the UI has nothing to segment.
        assert!(rc.contains("133;A"), "prompt-start marker missing");
        assert!(rc.contains("133;B"), "prompt-end marker missing");
        assert!(rc.contains("133;C"), "command-start marker missing");
        assert!(rc.contains("133;D"), "command-exit marker missing");
        assert!(rc.contains("]7;file://"), "cwd marker missing");
        // And it must not strand the user without their own config.
        assert!(rc.contains(".zshrc"), "user config is never sourced");

        let keys: Vec<&str> = env.iter().map(|(k, _)| k.as_str()).collect();
        assert!(keys.contains(&"ZDOTDIR"));
        assert!(
            args_for("/bin/zsh", &env).is_empty(),
            "zsh needs no extra args"
        );
    }

    #[test]
    fn bash_integration_uses_rcfile() {
        let _home = scratch_home("bash");
        let env = prepare("/bin/bash").expect("prepare bash");
        let args = args_for("/bin/bash", &env);
        assert_eq!(args[0], "--rcfile");
        assert!(args[1].ends_with("bashrc"));
        let rc = std::fs::read_to_string(&args[1]).unwrap();
        assert!(rc.contains("133;D"));
        // Login emulation must start where a real login bash does.
        assert!(
            rc.contains("/etc/profile"),
            "login emulation must read /etc/profile first"
        );
    }

    #[test]
    fn unknown_shell_degrades_quietly() {
        let _home = scratch_home("unknown");
        let env = prepare("/usr/bin/dash").expect("prepare dash");
        assert!(env.is_empty(), "no integration, but no error either");
    }

    #[test]
    fn fish_integration_uses_init_command() {
        let _home = scratch_home("fishint");
        let env = prepare("/opt/homebrew/bin/fish").expect("prepare fish");
        let init = env
            .iter()
            .find(|(k, _)| k == "TABVERSE_FISH_INIT")
            .map(|(_, v)| v.clone())
            .expect("fish announces its init file");
        let rc = std::fs::read_to_string(&init).unwrap();

        // Both marker families, or the UI has nothing to segment.
        assert!(rc.contains("133;A"), "prompt-start marker missing");
        assert!(rc.contains("133;B"), "prompt-end marker missing");
        assert!(rc.contains("133;C"), "command-start marker missing");
        assert!(rc.contains("133;D"), "command-exit marker missing");
        assert!(rc.contains("]7;file://"), "cwd marker missing");

        let args = args_for("/opt/homebrew/bin/fish", &env);
        let idx = args
            .iter()
            .position(|a| a == "-C")
            .expect("fish loads the integration through -C");
        assert_eq!(args[idx + 1], "source $TABVERSE_FISH_INIT");
        // The native-marker kill switch is version-gated: present exactly when
        // the local fish knows it, never as an unconditional bet that an old
        // fish tolerates an unknown value.
        if env.iter().any(|(k, _)| k == "TABVERSE_FISH_NO_MARK") {
            assert_eq!(args[0], "--features");
            assert_eq!(args[1], "no-mark-prompt");
        } else {
            assert!(
                !args.iter().any(|a| a == "--features"),
                "flag must not ride along for fish that never shipped it"
            );
        }
        assert!(
            env.iter().any(|(k, _)| k == "TABVERSE_SHELL_INTEGRATION"),
            "parity with zsh/bash: the shell can tell integration is on"
        );
    }

    #[test]
    fn pwsh_integration_is_file_level() {
        let _home = scratch_home("pwsh");
        let env = prepare("pwsh").expect("prepare pwsh");
        let init = env
            .iter()
            .find(|(k, _)| k == "TABVERSE_PWSH_INIT")
            .map(|(_, v)| v.clone())
            .expect("pwsh announces its init file");
        let script = std::fs::read_to_string(&init).unwrap();

        // The prompt wrapper must keep the user's own prompt runnable:
        // copy-then-invoke, not replace.
        assert!(
            script.contains("$function:prompt"),
            "original prompt reference missing"
        );
        assert!(
            script.contains("& $global:__tabverse_user_prompt"),
            "wrapped prompt must invoke the user's original"
        );
        assert!(
            script.contains("PSConsoleHostReadLine"),
            "readline override missing"
        );
        assert!(
            script.contains("cmdline_b64"),
            "base64 command line missing"
        );
        assert!(
            script.contains(".Path"),
            "OSC 7 must use .Path, not a provider path"
        );
        assert!(script.contains("133;A"));
        assert!(script.contains("133;B"));
        assert!(script.contains("133;C"));
        assert!(script.contains("133;D"));
        assert!(script.contains("]7;file://"));

        assert_eq!(
            args_for("pwsh", &env),
            vec![
                "-NoLogo".to_string(),
                "-NoExit".to_string(),
                "-Command".to_string(),
                ". $env:TABVERSE_PWSH_INIT".to_string(),
            ]
        );
    }

    #[test]
    fn fish_version_parses_the_last_field() {
        assert_eq!(fish_version("fish, version 4.5.0\n"), Some((4, 5, 0)));
        assert_eq!(fish_version("fish, version 3.7.1"), Some((3, 7, 1)));
        assert_eq!(fish_version("fish, version 4.0.6"), Some((4, 0, 6)));
        assert_eq!(fish_version("fish, version 4.0.5"), Some((4, 0, 5)));
        assert_eq!(fish_version("garbage"), None);
        // 4.0.6 shipped the flag; everything before does not.
        assert!((4, 0, 6) >= (4, 0, 6));
        assert!((4, 0, 5) < (4, 0, 6));
        assert!((5, 0, 0) >= (4, 0, 6));
    }
}
