const EXT_LANG: Record<string, string> = {
  ts: "typescript",
  tsx: "typescript",
  js: "javascript",
  jsx: "javascript",
  mjs: "javascript",
  cjs: "javascript",
  json: "json",
  jsonc: "json",
  md: "markdown",
  markdown: "markdown",
  html: "html",
  htm: "html",
  css: "css",
  scss: "scss",
  less: "less",
  rs: "rust",
  py: "python",
  go: "go",
  java: "java",
  kt: "kotlin",
  swift: "swift",
  c: "c",
  h: "c",
  cc: "cpp",
  cpp: "cpp",
  hpp: "cpp",
  m: "objective-c",
  mm: "objective-c",
  rb: "ruby",
  php: "php",
  sh: "shell",
  bash: "shell",
  zsh: "shell",
  fish: "shell",
  sql: "sql",
  yaml: "yaml",
  yml: "yaml",
  xml: "xml",
  svg: "xml",
  plist: "xml",
  env: "ini",
  properties: "ini",
  proto: "proto",
  graphql: "graphql",
  gql: "graphql",
  ipynb: "json",
  lua: "lua",
  dart: "dart",
  r: "r",
  cs: "csharp",
  scala: "scala",
  dockerfile: "dockerfile",
  toml: "ini",
  ini: "ini",
  conf: "ini",
  vue: "html",
};

export function languageFor(path: string): string {
  const base = path.split("/").pop() ?? "";
  if (/^dockerfile/i.test(base)) return "dockerfile";
  if (/^makefile/i.test(base)) return "makefile";
  const ext = base.includes(".") ? base.split(".").pop()!.toLowerCase() : "";
  return EXT_LANG[ext] ?? "plaintext";
}
